### ISSUE TITLE
motor motion fails to complete

### ISSUE THREAD

**Issue by prjemian** [prjemian/ipython-vm7#1]
Sometimes, motor motion fails to complete.  First noticed that recently when testing LivePlot problems for the USAXS, running a specific sequence of activities within an infinite loop.  At random time, the sequence waits indefinitely for the motor.  The motor is an EPICS soft motor record running in a self-hosted linux VM on the same workstation as the bluesky session.

In EPICS, the motor has reached position and the DMOV is 1.  In bluesky, the move is waiting to complete but has reached 100%.

This is the bluesky code:

```
In [12]: bluesky.__version__                                                                                                                
Out[12]: '1.5.4'

In [13]: ophyd.__version__                                                                                                                  
Out[13]: '1.3.3'

from ophyd import EpicsMotor
m1 = EpicsMotor('sky:m1', name='m1', labels=("motor",))

from bluesky import RunEngine
from bluesky.utils import get_history
RE = RunEngine(get_history())

from bluesky.callbacks.best_effort import BestEffortCallback
bec = BestEffortCallback()
RE.subscribe(bec)

def back_and_forth():
    i = 0
    while True:
        i += 1
        logger.info(f"forward: {i}")
        yield from bps.mv(m1, 1)
        logger.info("backward")
        yield from bps.mv(m1, -1)


RE(back_and_forth())
```

**Comment by prjemian** [comment]
This is the console output from running this code (failed during the second loop, `i=2`):

```
In [10]: RE(back_and_forth())                                                                                                               
I Tue-17:20:30 - forward: 1
INFO:bluesky-ipython-shell:forward: 1
                                                                                                                                            
I Tue-17:20:30 - backward
                                                                                                                                            
I Tue-17:20:32 - forward: 2
m1A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^CPausing...
---------------------------------------------------------------------------
RunEngineInterrupted                      Traceback (most recent call last)
<ipython-input-10-1d2308133908> in <module>
----> 1 RE(back_and_forth())

~/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    754 
    755             if self._interrupted:
--> 756                 raise RunEngineInterrupted(self.pause_msg) from None
    757 
    758         return tuple(self._run_start_uids)

RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.


In [11]: RE.abort()                                                                                                                         
Aborting: running cleanup and marking exit_status as 'abort'...
[E 17:20:44.838 run_engine:1257] Run aborted                                                                                                
    Traceback (most recent call last):
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1127, in _run
        self._exception or resp)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1147, in baseline_wrapper
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "<ipython-input-9-96aa46457aad>", line 6, in back_and_forth
        yield from bps.mv(m1, 1)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 247, in mv
        yield Msg('wait', None, group=group)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      [Previous line repeated 1 more time]
    bluesky.utils.RequestAbort
ERROR:bluesky.RE.140369946019088:Run aborted
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1127, in _run
    self._exception or resp)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
    return (yield from plan)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1147, in baseline_wrapper
    return (yield from plan)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
    return (yield from plan2)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "<ipython-input-9-96aa46457aad>", line 6, in back_and_forth
    yield from bps.mv(m1, 1)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 247, in mv
    yield Msg('wait', None, group=group)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 1 more time]
bluesky.utils.RequestAbort
Out[11]: []
```

**Comment by prjemian** [comment]
Want to record the console at the time the failure is observed (while the tqdm progress bar is showing).  That happened on the next run with `i=8` in the *forward* direction:

```
In [14]: RE(back_and_forth())                                                                                                               
I Tue-17:29:22 - forward: 1
INFO:bluesky-ipython-shell:forward: 1
I Tue-17:29:22 - backward
INFO:bluesky-ipython-shell:backward
                                                                                                                                            
I Tue-17:29:24 - forward: 2
                                                                                                                                            
I Tue-17:29:26 - backward
                                                                                                                                            
I Tue-17:29:29 - forward: 3
                                                                                                                                            
I Tue-17:29:31 - backward
                                                                                                                                            
I Tue-17:29:33 - forward: 4
                                                                                                                                            
I Tue-17:29:36 - backward
                                                                                                                                            
I Tue-17:29:38 - forward: 5
                                                                                                                                            
I Tue-17:29:40 - backward
                                                                                                                                            
I Tue-17:29:42 - forward: 6
                                                                                                                                            
I Tue-17:29:45 - backward
                                                                                                                                            
I Tue-17:29:47 - forward: 7
                                                                                                                                            
I Tue-17:29:49 - backward
                                                                                                                                            
I Tue-17:29:52 - forward: 8
m1: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 2.0/2.0 [00:02<00:00,  1.15s/degrees]
```

**Comment by prjemian** [comment]
screen looks like this:
![Clipboard01](https://user-images.githubusercontent.com/2279984/70098857-ebc44980-15f2-11ea-87a9-872373ebada6.jpg)

**Comment by prjemian** [comment]
Then, `^C^C` 

```
I Tue-17:29:47 - forward: 7
                                                                                                                                            
I Tue-17:29:49 - backward
                                                                                                                                            
I Tue-17:29:52 - forward: 8
m1A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
^CPausing...
---------------------------------------------------------------------------
RunEngineInterrupted                      Traceback (most recent call last)
<ipython-input-14-1d2308133908> in <module>
----> 1 RE(back_and_forth())

~/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    754 
    755             if self._interrupted:
--> 756                 raise RunEngineInterrupted(self.pause_msg) from None
    757 
    758         return tuple(self._run_start_uids)

RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.
```

and finally `RE.abort()`:

```
In [15]: RE.abort()                                                                                                                         
Aborting: running cleanup and marking exit_status as 'abort'...
[E 17:33:57.750 run_engine:1257] Run aborted                                                                                                
    Traceback (most recent call last):
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1127, in _run
        self._exception or resp)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1147, in baseline_wrapper
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "<ipython-input-9-96aa46457aad>", line 6, in back_and_forth
        yield from bps.mv(m1, 1)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 247, in mv
        yield Msg('wait', None, group=group)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      [Previous line repeated 1 more time]
    bluesky.utils.RequestAbort
ERROR:bluesky.RE.140369946019088:Run aborted
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1127, in _run
    self._exception or resp)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
    return (yield from plan)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1147, in baseline_wrapper
    return (yield from plan)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
    return (yield from plan2)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
    return (yield from plan2)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File "<ipython-input-9-96aa46457aad>", line 6, in back_and_forth
    yield from bps.mv(m1, 1)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 247, in mv
    yield Msg('wait', None, group=group)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
    inner_ret = yield msg
  [Previous line repeated 1 more time]
bluesky.utils.RequestAbort
Out[15]: []
```

**Comment by prjemian** [comment]
Here's what line 194 (and nearby) looks like in the code that fails:
![Clipboard01](https://user-images.githubusercontent.com/2279984/70099071-79a03480-15f3-11ea-914f-3db6cfe9a438.jpg)

**Comment by prjemian** [comment]
So, it is waiting because some status message (presume it is related to motor *m1*) is not finished?

**Comment by prjemian** [comment]
Looks like the same problem as https://github.com/aps-8id-trr/ipython-8idiuser/issues/114, marking as duplicate.

**Comment by prjemian** [comment]
Now, I'm not convinced this is a duplicate of https://github.com/aps-8id-trr/ipython-8idiuser/issues/114 but rather another matter.

**Comment by prjemian** [comment]
Filed as an ophyd issue, closing here.
